
shinyUI(
  
  pageWithSidebar(
    
    # Application title
    headerPanel(
      list(HTML('<img src="icon.jpg" style="width: 90%; height: 20%" />'), 
           "Delitos en Zapopan - PETRUS"
      ),
      windowTitle="PETRUS"  ),
    

    sidebarPanel(
      
      h3("Selecciona los datos"),
      
      selectInput(inputId="colonia",label="Nombre de la colonia",
                  list(
                    "12 DE DICIEMBRE",
                    "AGRICOLA",
                    "AGUA BLANCA",
                    "AGUA BLANCA INDUSTRIAL",
                    "AGUA BLANCA SUR",
                    "AGUA FRIA",
                    "AGUILAS LAS",
                    "AGUJAS LAS",
                    "ALAMEDAS LAS",
                    "ALAMITOS LOS",
                    "ALAMO",
                    "ALBATERRA",
                    "ALMENDROS LOS",
                    "ALTAGRACIA",
                    "ALTAMIRA",
                    "ALTAVISTA",
                    "AMARANTO",
                    "AMPLIACION SANTA LUCIA",
                    "ANGELES DE NEXTIPAC LOS",
                    "ARBOLEDA LA",
                    "ARBOLEDAS",
                    "ARCOS DE GUADALUPE",
                    "ARCOS DE ZAPOPAN",
                    "ARENALES TAPATIOS",
                    "ARMONIA",
                    "ARROYO HONDO",
                    "ATEMAJAC DEL VALLE",
                    "ATLAS COLOMOS",
                    "AUDITORIO",
                    "AURORA LA",
                    "AYAMONTE",
                    "BAJIO EL",
                    "BALCONES DE LA CANTERA",
                    "BALCONES DEL SOL",
                    "BATAN EL",
                    "BENITO JUAREZ",
                    "BENITO JUAREZ NORTE",
                    "BOSQUE DE LA PRIMAVERA",
                    "BOSQUE ESCONDIDO",
                    "BOSQUE LA PRIMAVERA S-III",
                    "BOSQUES DEL CENTINELA",
                    "BOVEDAS LAS",
                    "BRISAS DE LA PRIMAVERA",
                    "BRISEniO EL",
                    "BUGAMBILIAS",
                    "BUGAMBILIAS COUNTRY",
                    "CABAniITAS",
                    "CABECERA MUNICIPAL",
                    "CAJETES LOS",
                    "CALMA LA",
                    "CAMACHOS LOS",
                    "CAMICHINES VALLARTA",
                    "CAMINO REAL",
                    "CAMPANARIO EL",
                    "CAMPESTRE LOS PINOS",
                    "CANTERAS DEL CENTINELA",
                    "CANTEROS LOS",
                    "CAPULLO EL",
                    "CARLOS RIVERA ACEVES",
                    "CARRETERA A COLOTLAN",
                    "CARRETERA A NEXTIPAC",
                    "CARRETERA A NOGALES",
                    "CARRETERA A SALTILLO",
                    "CARRIZAL EL",
                    "CASA GRANDE",
                    "CASITAS LAS",
                    "CASTAniOS LOS",
                    "CENTINELA EL",
                    "CENTRO COMERCIAL SORIANA",
                    "CERRITOS LOS",
                    "CHAPALITA",
                    "CHAPALITA DE OCCIDENTE",
                    "CHAPALITA INN",
                    "CHAPALITA SUR",
                    "CIMA LA",
                    "CIUDAD BUGAMBILIAS",
                    "CIUDAD DE LOS NIniOS",
                    "CIUDAD DEL SOL",
                    "CIUDAD GRANJA",
                    "CIUDAD JUDICIAL",
                    "COLEGIO DEL AIRE",
                    "COLINAS DE ATEMAJAC",
                    "COLINAS DE LA PRIMAVERA",
                    "COLINAS DE LAS AGUILAS",
                    "COLINAS DE LOS BELENES",
                    "COLINAS DE LOS ROBLES",
                    "COLINAS DEL REY",
                    "COLINAS DEL RIO",
                    "COLLI CTM",
                    "COLLI EL",
                    "COLLI PRIMAVERA",
                    "COLLI SITIO",
                    "CONCENTRO",
                    "CONDO PLAZA DEL SOL",
                    "CONJUNTO BELENES",
                    "CONJUNTO LAURELES",
                    "CONJUNTO PATRIA",
                    "CONJUNTO RITZ",
                    "CONJUNTO ZAPOPAN",
                    "CONSTITUCION",
                    "COPALA",
                    "CORONILLA DEL OCOTE LA",
                    "CORONILLA LA",
                    "COTO LOS ROBLES",
                    "DIVISION DEL NORTE",
                    "DON BOSCO VALLARTA",
                    "EJIDO COPALITA",
                    "EMILIANO ZAPATA",
                    "ESTADIO OMNILIFE",
                    "ESTANCIA LA",
                    "ESTRADA LA",
                    "EUCALIPTO VALLARTA",
                    "EXHACIENDA DEL LAZO",
                    "EXPERIENCIA LA",
                    "EXTRAMUROS",
                    "FLAMINGOS LOS",
                    "FLORES DEL VALLE",
                    "FLORES LAS",
                    "FLORESTA LA",
                    "FLORIDA LA",
                    "FORTIN EL",
                    "FRAILES LOS",
                    "FRANCISCO SARABIA",
                    "FRANCISCO VILLA",
                    "FRESNO EL",
                    "FUENTECILLAS",
                    "FUENTES LAS",
                    "GARABATO EL",
                    "GIRALDA LA",
                    "GIRASOLES",
                    "GIRASOLES ACUEDUCTO LOS",
                    "GIRASOLES ELITE",
                    "GLORIA DEL COLLI LA",
                    "GONZALEZ ORTEGA",
                    "GRANA LA",
                    "GUADALAJARITA",
                    "GUADALUPANA",
                    "GUADALUPE INN",
                    "GUADALUPE JARDIN",
                    "GUSA LA",
                    "GUSTAVO DIAZ ORDAZ",
                    "HACIENDA LA MORA",
                    "HACIENDA SAN ACASIO",
                    "HACIENDAS DE ZAPOPAN",
                    "HACIENDAS DEL VALLE",
                    "HACIENDAS TEPEYAC",
                    "HACIENDITA",
                    "HEROES NACIONALES",
                    "HIGUERA LA",
                    "HOGARES DE NUEVO MEXICO",
                    "HUAXTLA",
                    "HUMEDO EL",
                    "INDIGENA DE MEZQUITAN",
                    "INDUSTRIAL BELENES",
                    "INDUSTRIAL BELENES NORTE",
                    "INDUSTRIAL ZAPOPAN NORTE",
                    "IXCATAN",
                    "JACARANDAS",
                    "JARDIN REAL",
                    "JARDINES DE BELEN",
                    "JARDINES DE GUADALUPE",
                    "JARDINES DE LA ESPERANZA",
                    "JARDINES DE LA PATRIA",
                    "JARDINES DE LAS FUENTES",
                    "JARDINES DE LOS BELENES",
                    "JARDINES DE NUEVO MEXICO",
                    "JARDINES DE SAN ANTONIO",
                    "JARDINES DE SAN IGNACIO",
                    "JARDINES DE SANTA ANA",
                    "JARDINES DEL IXTEPETE",
                    "JARDINES DEL PORVENIR",
                    "JARDINES DEL SOL",
                    "JARDINES DEL VALLE",
                    "JARDINES DEL VERGEL",
                    "JARDINES SEATTLE",
                    "JARDINES TAPATIOS",
                    "JARDINES TEPEYAC",
                    "JARDINES UNIVERSIDAD",
                    "JARDINES VALLARTA",
                    "JOCOTAN",
                    "JUAN MANUEL VALLARTA",
                    "LA GRAN PLAZA",
                    "LA PATRIA UNIVERSIDAD",
                    "LAGOS DEL COUNTRY",
                    "LINDAVISTA",
                    "LOMA BLANCA",
                    "LOMA BONITA",
                    "LOMA BONITA EJIDAL",
                    "LOMA BONITA RESIDENCIAL",
                    "LOMA BONITA SUR",
                    "LOMA CHICA",
                    "LOMA LA",
                    "LOMAS ALTAS",
                    "LOMAS DE ATEMAJAC",
                    "LOMAS DE GUADALUPE",
                    "LOMAS DE LA PRIMAVERA",
                    "LOMAS DE SAN GONZALO",
                    "LOMAS DE TABACHINES",
                    "LOMAS DE TESISTAN",
                    "LOMAS DE ZAPOPAN",
                    "LOMAS DEL BATAN",
                    "LOMAS DEL BOSQUE",
                    "LOMAS DEL CENTINELA",
                    "LOMAS DEL COLLI",
                    "LOMAS DEL REFUGIO",
                    "LOMAS DEL SEMINARIO",
                    "LOMAS DEL VALLE",
                    "LOMAS UNIVERSIDAD",
                    "MAESTROS LOS",
                    "MAGDALENA LA",
                    "MANTE EL",
                    "MANZANOS LOS",
                    "MARCELINO GARCIA BARRAGAN",
                    "MARIANO OTERO",
                    "MARTELL DEL VALLE",
                    "MARTINICA LA",
                    "MESA COLORADA",
                    "MESA COLORADA PONIENTE",
                    "MESA DE LOS OCOTES",
                    "MESA DE SAN JUAN",
                    "MIGUEL DE LA MADRID HURTADO",
                    "MIGUEL HIDALGO",
                    "MILPILLAS",
                    "MIRADOR DE SAN ISIDRO",
                    "MIRADOR DEL BOSQUE",
                    "MIRADOR DEL SOL",
                    "MIRADOR ESCONDIDO",
                    "MIRAMAR",
                    "MISION DEL BOSQUE",
                    "MISION DEL VALLE",
                    "MISION LA FLORESTA",
                    "MOJONERA LA",
                    "MOLINO DEL SALVADOR",
                    "MOLINOS LOS",
                    "NEXTIPAC",
                    "NUCLEO BELENES",
                    "NUEVA ESPAniA",
                    "NUEVA GALICIA",
                    "NUEVA PRIMAVERA",
                    "NUEVO MEXICO",
                    "NUEVO VERGEL",
                    "OLIVOS RESIDENCIAL",
                    "PACIFICA HABITAT",
                    "PALERMO",
                    "PALMIRA LA",
                    "PALMITA LA",
                    "PARAISOS DEL COLLI",
                    "PARAISOS LOS",
                    "PARQUE METROPOLITANO",
                    "PARQUES DE GUADALUPE",
                    "PARQUES DE TESISTAN",
                    "PARQUES DE ZAPOPAN",
                    "PARQUES DEL AUDITORIO",
                    "PARQUES DEL CENTINELA",
                    "PARQUES TEPEYAC",
                    "PASEOS DEL BRISEniO",
                    "PASEOS DEL CAMICHIN",
                    "PASEOS DEL SOL",
                    "PASEOS UNIVERSIDAD",
                    "PATIO LA CIMA",
                    "PATIO PATRIA",
                    "PEDRO MORENO",
                    "PERIODISTAS",
                    "PINAR DE LA CALMA",
                    "PINAR DE LA VENTA",
                    "PINOS LOS",
                    "PIRAMIDES LAS",
                    "PLAZA ACUEDUCTO",
                    "PLAZA ANDARES",
                    "PLAZA BELENES",
                    "PLAZA CIUDADELA",
                    "PLAZA CORDILLERAS",
                    "PLAZA DEL SOL",
                    "PLAZA GALERIAS",
                    "PLAZA GUADALUPE",
                    "PLAZA PATRIA",
                    "PLAZA PUNTO SAN ISIDRO",
                    "PLAZA SAN ISIDRO",
                    "PLAZA SANTA MARGARITA",
                    "PLAZA TEPEYAC",
                    "PONTEVEDRA",
                    "PORTA REAL",
                    "PRADERAS DE TESISTAN",
                    "PRADOS DE SANTA LUCIA",
                    "PRADOS TEPEYAC",
                    "PRADOS VALLARTA",
                    "PRIMAVERA LA",
                    "PUERTA DE HIERRO",
                    "PUERTA DEL BOSQUE",
                    "PUERTA DEL LLANO",
                    "PUERTA DEL ROBLE",
                    "PUERTA DEL VALLE",
                    "PUERTA REAL",
                    "PUESTA DEL SOL",
                    "QUINTA DEL FEDERALISMO",
                    "RANCHO COLORADO",
                    "RANCHO CONTENTO",
                    "RANCHO EL CENTINELA",
                    "REAL ACUEDUCTO",
                    "REAL DE VALDEPEniAS",
                    "REAL DEL BOSQUE",
                    "REAL DEL CARMEN",
                    "REAL VALLARTA",
                    "REHILETE EL",
                    "RESIDENCIAL DEL BOSQUE",
                    "RESIDENCIAL DEL PARQUE",
                    "RESIDENCIAL DEL VALLE",
                    "RESIDENCIAL MOCTEZUMA",
                    "RESIDENCIAL MOCTEZUMA PONIENTE",
                    "RESIDENCIAL PATRIA",
                    "RESIDENCIAL PLAZA GUADALUPE",
                    "RESIDENCIAL PONIENTE",
                    "RESIDENCIAL REAL LAS PALOMAS",
                    "RESIDENCIAL SANTA MARGARITA",
                    "RESIDENCIAL TABACHINES",
                    "RESIDENCIAL VICTORIA",
                    "RESIDENCIAL VIRREYES",
                    "REVOLUCION",
                    "RINCONADA DE LA CALMA",
                    "RINCONADA DEL AUDITORIO",
                    "RINCONADA DEL PARQUE",
                    "RINCONADA DEL SOL",
                    "RINCONADA DEL VALLE",
                    "RINCONADA GUADALUPE",
                    "RINCONADA LAS PALMAS",
                    "RINCONADA SAN ISIDRO",
                    "RINCONADA SANTA RITA",
                    "RINCONADAS DE ZAPOPAN",
                    "RIO BLANCO",
                    "ROBERTO OROZCO",
                    "ROBLES LOS",
                    "ROYAL COUNTRY",
                    "SAN BERNARDO",
                    "SAN ESTEBAN",
                    "SAN FRANCISCO",
                    "SAN GILBERTO",
                    "SAN ISIDRO EJIDAL",
                    "SAN ISIDRO RESIDENCIAL",
                    "SAN JOSE DEL BAJIO",
                    "SAN JOSE EJIDAL",
                    "SAN JUAN DE OCOTAN",
                    "SAN MIGUEL DE LA COLINA",
                    "SAN MIGUEL TATEPOSCO",
                    "SAN NICOLAS DE LOS BELENES",
                    "SAN WENCESLAO",
                    "SANTA ANA TEPETITLAN",
                    "SANTA CATALINA",
                    "SANTA FE",
                    "SANTA ISABEL",
                    "SANTA LUCIA",
                    "SANTA MARGARITA",
                    "SANTA MARIA DEL PUEBLITO",
                    "SANTA MONICA DE LOS CHORRITOS",
                    "SEATTLE",
                    "SOLARES",
                    "SOLEDAD LA",
                    "TABACHINES",
                    "TECHNOLOGY PARK",
                    "TEPEYAC",
                    "TEPEYAC CASINO",
                    "TESISTAN",
                    "TIGRE EL",
                    "TIZATE EL",
                    "TRIANGULO EL",
                    "TULE EL",
                    "TUZANIA LA",
                    "UNIDAD ABASTOS",
                    "UNIDAD FOVISSSTE",
                    "UNIDAD LOPEZ PORTILLO",
                    "UNIDAD MEXICO",
                    "UNIDAD REPUBLICA",
                    "UNIDAD UAG",
                    "VALLARTA LA PATRIA",
                    "VALLARTA UNIVERSIDAD",
                    "VALLE DE LA PROVIDENCIA",
                    "VALLE DE LOS MOLINOS",
                    "VALLE DE NUEVO MEXICO",
                    "VALLE DE SAN ISIDRO",
                    "VALLE DE SAN NICOLAS",
                    "VALLE ESCONDIDO",
                    "VALLE ESMERALDA",
                    "VALLE IMPERIAL",
                    "VALLE REAL",
                    "VEINTISIETE DE SEPTIEMBRE",
                    "VENTA DEL ASTILLERO LA",
                    "VENUSTIANO CARRANZA",
                    "VICENTE GUERRERO",
                    "VICTOR HUGO",
                    "VIGIA EL",
                    "VILLA LA",
                    "VILLA SERENA",
                    "VILLA UNIVERSITARIA",
                    "VILLA VERONA",
                    "VILLAS ALCALDE",
                    "VILLAS DE GUADALUPE",
                    "VILLAS DE LOS BELENES",
                    "VILLAS DE NUEVO MEXICO",
                    "VILLAS DE TESISTAN",
                    "VILLAS DE TORREMOLINOS",
                    "VILLAS DEL CENTINELA",
                    "VILLAS DEL IXTEPETE",
                    "VILLAS DEL MIRADOR",
                    "VILLAS DEL VALLE",
                    "VILLAS LA LOMA",
                    "VILLAS PERISUR",
                    "VILLAS TEPEYAC",
                    "VISTA HERMOSA",
                    "VISTAS DE TESISTAN",
                    "VISTAS DEL BOSQUE",
                    "VOLCAN DEL COLLI",
                    "ZAPOTE EL",
                    "ZOQUIPAN")
                    , selected='ALTAVISTA')
      ,
      

      
      selectInput("dia.sem", "Día de la semana",
                  list( "Mon" ,  "Tue", "Wed", "Fri", "Sat" ,"Sun")),
      
      selectInput("cat", "Nivel de inseguridad",
                  list("Todos", "Muy baja", "Baja", "Media","Alta","Muy alta" ))
      
      
    )#slider
    ,
    
    mainPanel(
      
      
      h3('Heat map'),
      
      plotOutput("plot", width = "100%", height = "420px"),
      br(),
      br(),
      br(),
      
      p("Creado por:",
        a("Carlos Petricioli", href = "http://github.com/carpetri"), 'y', 
        a("Christopher Lazarus", href = "http://clazarus.com") )
      
      # downloadButton('reporte','Reporte')
      
      
      
    )))